import js from '@eslint/js'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

/**
 * ESLint flat config for the zemu-launcher renderer.
 *
 * Notable carve-outs:
 *
 *   1. `src/components/ui/**` and `src/hooks/use-mobile.ts` — generated by
 *      `npx shadcn add ...`. Disabling rules here means we don't fork
 *      upstream source (which would mean re-applying our patches on every
 *      `shadcn add ...` run).
 *
 *   2. `scripts/**` — Node.js build/release scripts. Linted separately if
 *      at all; ESLint's renderer config doesn't apply to them and the
 *      Node globals (`__dirname`, `process`, etc.) would just produce
 *      noise.
 *
 *   3. Browser DOM globals — `tsconfig.json`'s `lib: ["DOM"]` tells
 *      TypeScript about `SVGSVGElement`, `HTMLDivElement`, etc., but
 *      ESLint's `no-undef` runs against its own globals table and needs
 *      them declared explicitly.
 *
 *   4. `react-hooks/set-state-in-effect` — disabled project-wide because
 *      every existing dialog, route, and state-reset effect follows the
 *      "synchronize from props on mount/prop-change" pattern, which is
 *      documented as a valid use of effects. The rule's antipattern is
 *      "set state to mirror state you already have" — our effects are
 *      either resetting form state on dialog close or seeding from
 *      initial props, which are not the antipattern.
 *
 *   5. `react-hooks/refs` — disabled for `news-slider.tsx` because the
 *      slider intentionally reads `dragStartX.current` during render to
 *      decide whether to show the live drag transform. React's docs
 *      recommend refs for high-frequency gesture state precisely because
 *      reading them doesn't trigger a re-render.
 */
export default [
  {
    ignores: [
      'dist',
      'src-tauri',
      'release',
      'node_modules',
      'scripts',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tsparser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // Runtime browser globals.
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        navigator: 'readonly',
        process: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        queueMicrotask: 'readonly',
        Response: 'readonly',
        DOMParser: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        React: 'readonly',
        // DOM type constructors used in `React.HTMLAttributes<...>`
        // generic constraints and elsewhere. ESLint's no-undef needs
        // them declared even though they're types, not values — they're
        // global names in TypeScript's DOM lib.
        SVGSVGElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        FocusEvent: 'readonly',
        AnimationEvent: 'readonly',
        TransitionEvent: 'readonly',
        UIEvent: 'readonly',
        ClipboardEvent: 'readonly',
        DragEvent: 'readonly',
        PointerEvent: 'readonly',
        TouchEvent: 'readonly',
        WheelEvent: 'readonly',
        MediaQueryListEvent: 'readonly',
        Node: 'readonly',
        HTMLElementTagNameMap: 'readonly',
      },
    },
    settings: { react: { version: '18.2' } },
    plugins: {
      '@typescript-eslint': tseslint,
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'react/prop-types': 'off',
      // Apostrophes in JSX text are common in editorial content (news
      // posts, marketing copy). Escaping every one with `&apos;` makes
      // prose harder to read and review. Leaving this on `error` would
      // just push work onto anyone editing copy.
      'react/no-unescaped-entities': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // Disabled project-wide — see carve-out #4 in the comment above.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // shadcn-generated code: see carve-out #1.
    files: ['src/components/ui/**/*.{ts,tsx}', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // Context providers export both a `<Provider>` component and a
    // `useXxxContext` hook in the same file. That's the canonical
    // context-file shape and there's nothing to fix without splitting
    // the file in two, which adds noise for no HMR benefit (context
    // providers are mounted once at the root).
    files: ['src/contexts/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // The slider intentionally reads `dragStartX.current` during render
    // to drive the live drag transform — see carve-out #5.
    files: ['src/components/news-slider.tsx'],
    rules: {
      'react-hooks/refs': 'off',
    },
  },
]
