import js from '@eslint/js'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

/**
 * ESLint flat config for the zemu-launcher renderer.
 *
 * Two notable carve-outs:
 *
 *   1. `src/components/ui/**` — generated by `npx shadcn add ...` and
 *      verbatim from the upstream shadcn registry. We disable
 *      `react-refresh/only-export-components` and
 *      `react-hooks/set-state-in-effect` here so the launcher's lint
 *      stays clean without forking upstream source. Touching these
 *      files would mean re-applying our patches on every
 *      `shadcn add ...` run, which is brittle.
 *
 *   2. Browser DOM globals — `tsconfig.json`'s `lib: ["DOM"]` tells
 *      TypeScript about `SVGSVGElement`, `HTMLDivElement`, etc., but
 *      ESLint's `no-undef` rule runs against its own globals table
 *      and needs them declared explicitly. The list below covers
 *      every DOM type our renderer-side code references.
 */
export default [
  { ignores: ['dist', 'src-tauri', 'release', 'node_modules'] },
  js.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tsparser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // Runtime browser globals.
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        process: 'readonly',
        localStorage: 'readonly',
        crypto: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        React: 'readonly',
        // DOM type constructors used in `React.HTMLAttributes<...>`
        // generic constraints. ESLint's no-undef needs them declared
        // even though they're types, not values — they're global
        // names in TypeScript's DOM lib.
        SVGSVGElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        FocusEvent: 'readonly',
        AnimationEvent: 'readonly',
        TransitionEvent: 'readonly',
        UIEvent: 'readonly',
        ClipboardEvent: 'readonly',
        DragEvent: 'readonly',
        PointerEvent: 'readonly',
        TouchEvent: 'readonly',
        WheelEvent: 'readonly',
        MediaQueryListEvent: 'readonly',
        Node: 'readonly',
        HTMLElementTagNameMap: 'readonly',
      },
    },
    settings: { react: { version: '18.2' } },
    plugins: {
      '@typescript-eslint': tseslint,
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'react/prop-types': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
  // shadcn-generated code (both `src/components/ui/**` and the
  // shadcn-shipped hooks under `src/hooks/`) shouldn't be forked to
  // satisfy lint rules. Two upstream issues don't make sense to fix
  // in our tree:
  //   - react-refresh/only-export-components: many shadcn files
  //     export both a Component and a CVA variant object. The
  //     warning is fine in dev — it just means HMR is slower for
  //     those files. Turning it off here keeps the launcher lint
  //     clean without forking upstream.
  //   - react-hooks/set-state-in-effect: shadcn's use-mobile and
  //     carousel hooks intentionally set state synchronously in an
  //     effect to mirror the existing event-driven state model. The
  //     newer rule treats this as an antipattern, but for these
  //     generated files we'd rather just keep upstream behavior.
  {
    files: ['src/components/ui/**/*.{ts,tsx}', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
]