mod api;
mod auth;
mod child_process;
mod client_config;
mod commands;
// Compile-time URL/protocol constants emitted by `build.rs` from
// `update-config.json` and `src/config/launcher.ts`. The file is
// generated to `$OUT_DIR/config.rs`; this `include!` exposes it
// as `crate::config::*`. There is no hand-written `config.rs` in
// this directory — editing the source files instead will produce
// a fresh copy via `cargo:rerun-if-changed` directives in
// `build.rs`.
#[allow(clippy::module_inception)]
mod config {
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}
mod debug_log;
mod depot;
mod dev_env;
mod discord;
mod friends;
mod friends_debug_log;
mod friends_realtime;
mod game;
mod hardware;
mod hardware_api;
mod http;
mod integrity;
mod launch_args;
mod models;
mod oauth_server;
mod process_integrity;
mod public_api;
mod state;
mod steam;
mod storage;
mod tpm;
mod update;
mod wine;

use state::AppState;
use tauri::{WebviewUrl, WebviewWindowBuilder};
use tauri_plugin_autostart::MacosLauncher;
use tauri_plugin_deep_link::DeepLinkExt;
use url::Url;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Load dev-only env overrides from `.env.local` BEFORE anything
    // else. The Rust side doesn't read Vite's `.env.local` natively;
    // this is the bridge that lets `LAUNCHER_API_BASE_URL` (and any
    // other dev-only override) flow into `std::env::var(...)` calls.
    // Production bundles ship without `.env.local`, so a missing file
    // is a no-op. See `dev_env.rs` for the full rationale.
    if let Err(error) = dev_env::load() {
        eprintln!("[dev_env] load failed: {error}");
    }

    // URL sources come from `crate::config` (generated by
    // `build.rs` from `update-config.json` + `src/config/launcher.ts`)
    // — there is no longer a renderer-reachable setter for any of
    // them. Dev overrides flow through env vars loaded by
    // `dev_env::load()` above; production builds have no override
    // path, which is the whole point of this refactor.
    let runtime_update_url = std::env::var("LAUNCHER_UPDATE_BASE_URL")
        .ok()
        .map(|v| v.trim().trim_end_matches('/').to_string())
        .filter(|v| !v.is_empty())
        .or_else(|| Some(crate::config::UPDATE_BASE_URL.to_string()));
    let realtime_url = std::env::var("LAUNCHER_REALTIME_URL")
        .ok()
        .map(|v| v.trim().trim_end_matches('/').to_string())
        .filter(|v| !v.is_empty())
        .or_else(|| Some(crate::config::REALTIME_URL.to_string()));

    let app_state = AppState::new(runtime_update_url, realtime_url);

    // One-shot shutdown channel. When the app exits, the `Sender` is dropped
    // and `rx.await` resolves, stopping the socket loop cleanly.
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel::<()>();
    // Keep the sender alive for the lifetime of the app. Dropping it at
    // app exit will close the channel and wake the socket loop.
    std::mem::forget(shutdown_tx);

    tauri::Builder::default()
        .plugin(tauri_plugin_keyring_store::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_single_instance::init(|app, args, _cwd| {
            commands::focus_primary_window(app);

            let protocol_prefix = configured_protocol_prefix(app);
            if let Some(url) = args
                .iter()
                .find(|arg| is_oauth_callback_arg(arg, protocol_prefix.as_deref()))
            {
                handle_protocol_url(app, url);
            }
        }))
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            Some(vec!["--autostart"]),
        ))
        .manage(app_state.clone())
        .invoke_handler(commands::register_commands())
        .setup(move |app| {
            // Both windows load the same `index.html` and route via
            // `getCurrentWindow().label` inside `App.tsx`. We construct
            // them explicitly (with `create: false` in `tauri.conf.json`)
            // so we control the URL handed to the webview.
            //
            // URL strategy:
            //
            //   * `tauri dev` — point both windows at the Vite dev server
            //     defined by `build.devUrl` in `tauri.conf.json`
            //     (typically `http://localhost:5173`).
            //
            //   * release builds — use `WebviewUrl::App("index.html")`,
            //     which goes through Tauri's in-process asset protocol
            //     handler and is webview-agnostic.
            //
            // Why not the obvious "http://tauri.localhost/index.html"
            // form? That host is a Tauri-runtime convention: WebView2
            // (Windows) and WKWebView (macOS) rewrite it to the asset
            // protocol automatically. **WebKitGTK (Linux) does not.**
            // On Linux, that URL is sent out as a real HTTP request to
            // `127.0.0.1:80`, where anything bound (commonly nginx,
            // serving its "Welcome to nginx!" default page) answers and
            // the React app never loads. `WebviewUrl::App` bypasses the
            // magic host and routes directly to the asset handler on
            // every backend.
            let bootstrap_url = build_index_url(app.config().build.dev_url.as_ref())?;
            let main_url = bootstrap_url.clone();

            // Bootstrap window: 460x430, frameless, always on top.
            // The React tree draws the rounded card; the OS window is
            // the surrounding layer.
            //
            // On Windows and macOS we set `transparent(true)` so the
            // React tree's `bg-transparent` outer div lets the desktop
            // show through, leaving only the rounded card visible.
            // Wry implements that via a `softbuffer` composite layer
            // (see `tauri-runtime-wry-2.11.4/src/lib.rs:4700`).
            //
            // On Linux WebKitGTK there is no equivalent layer — wry
            // skips the softbuffer path on this platform (the
            // `is_window_transparent` branch in wry is `#[cfg(windows)]`).
            // Passing `transparent(true)` there asks GTK to create an
            // alpha-transparent surface that WebKitGTK then renders an
            // opaque `bg-background` card on top of, and the surround
            // shows as solid black (because no compositor-level alpha
            // is available). We drop `transparent(true)` on Linux and
            // rely on WebKitGTK's default opaque surface; the bootstrap
            // card's own `bg-background` colour paints the surround.
            //
            // `decorations(false)` and `shadow(false)` stay enabled on
            // every platform — they don't require a transparency
            // pipeline and produce the intended frameless look on
            // Linux, where the surround simply shows as opaque white
            // (or whatever the dark-mode `bg-background` resolves to).
            //
            // `transparent(true)` MUST be set on the builder because
            // we construct the window ourselves with `create: false`
            // in tauri.conf.json — the config's `transparent` field
            // is only honored when Tauri auto-creates the window.
            #[allow(unused_mut)]
            let mut bootstrap_builder = WebviewWindowBuilder::new(app, "bootstrap", bootstrap_url)
                .title("ZEmu Launcher")
                .inner_size(460.0, 430.0)
                .resizable(false)
                .maximizable(false)
                .minimizable(false)
                .closable(true)
                .decorations(false)
                .shadow(false)
                .always_on_top(true)
                .skip_taskbar(true)
                .center()
                .visible(true);
            #[cfg(not(target_os = "linux"))]
            {
                bootstrap_builder = bootstrap_builder.transparent(true);
            }
            bootstrap_builder.build()?;
            app_state.mark_bootstrap_active();

            // Main window: 1280x800, frameless. The React tree draws
            // the rounded wrapper + close/minimize buttons. Same
            // transparency caveat as the bootstrap window above.
            #[allow(unused_mut)]
            let mut main_builder = WebviewWindowBuilder::new(app, "main", main_url)
                .title("ZEmu Launcher")
                .inner_size(1280.0, 800.0)
                .resizable(false)
                .maximizable(false)
                .minimizable(true)
                .closable(true)
                .decorations(false)
                .shadow(false)
                .center()
                .visible(false);
            #[cfg(not(target_os = "linux"))]
            {
                main_builder = main_builder.transparent(true);
            }
            main_builder.build()?;

            discord::initialize(app.handle());
            if let Err(error) = discord::set_in_launcher(app.handle()) {
                eprintln!("[startup] failed to queue initial launcher activity: {error}");
            }

            // Start the friends realtime socket. Runs in the background,
            // reconnecting with exponential back-off until the app exits.
            friends_realtime::spawn(app.handle().clone(), shutdown_rx);

            #[cfg(any(target_os = "linux", windows))]
            {
                if let Err(error) = app.deep_link().register_all() {
                    eprintln!("[startup] deep_link register_all failed: {error}");
                }
            }

            let app_handle = app.handle().clone();
            let _ = app.deep_link().on_open_url(move |event| {
                for url in event.urls() {
                    handle_protocol_url(&app_handle, url.as_str());
                }
            });

            let startup_args: Vec<String> = std::env::args().collect();
            let protocol_prefix = configured_protocol_prefix(app.handle());
            if let Some(url) = startup_args
                .iter()
                .find(|arg| is_oauth_callback_arg(arg, protocol_prefix.as_deref()))
            {
                handle_protocol_url(app.handle(), url);
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// Build the `WebviewUrl` both windows should load.
///
/// In `tauri dev`, `tauri.conf.json`'s `build.devUrl` is `Some(...)`
/// (e.g. `http://localhost:5173`) and we point straight at the Vite
/// dev server. In a release build, `devUrl` is `None` and we use
/// `WebviewUrl::App("index.html")`, which routes through Tauri's
/// in-process asset protocol handler — webview-agnostic, works on
/// WebView2, WKWebView, and WebKitGTK alike.
fn build_index_url(dev_url: Option<&url::Url>) -> tauri::Result<WebviewUrl> {
    #[cfg(dev)]
    {
        let base = dev_url
            .ok_or_else(|| {
                tauri::Error::Anyhow(anyhow::anyhow!(
                    "tauri.conf.json must define build.devUrl in dev builds"
                ))
            })?
            .to_string();
        let url = if base.ends_with('/') {
            format!("{base}index.html")
        } else {
            format!("{base}/index.html")
        };
        let parsed = Url::parse(&url)
            .map_err(|e| tauri::Error::Anyhow(anyhow::anyhow!("invalid index url {url:?}: {e}")))?;
        Ok(WebviewUrl::External(parsed))
    }

    #[cfg(not(dev))]
    {
        let _ = dev_url;
        Ok(WebviewUrl::App("index.html".into()))
    }
}

fn configured_protocol_prefix(_app: &tauri::AppHandle) -> Option<String> {
    // The deep-link scheme is now a compile-time constant from
    // `crate::config::OAUTH_CALLBACK_PROTOCOL` (set by `build.rs`
    // from `src/config/launcher.ts`). It used to be persisted to
    // `launcher-config.json` and read back via
    // `storage::detect_oauth_callback_protocol` — that path was
    // removed because (a) the only writer was the renderer pushing
    // the bundled default back to Rust, and (b) reading the
    // persisted value would let a stale / tampered config file
    // re-point the launcher at a different scheme on next launch.
    Some(crate::config::OAUTH_CALLBACK_PROTOCOL.to_string())
}

fn is_oauth_callback_arg(raw: &str, protocol_prefix: Option<&str>) -> bool {
    if let Some(prefix) = protocol_prefix {
        return raw.starts_with(prefix);
    }

    raw.contains("://oauth/callback")
}

fn handle_protocol_url(app: &tauri::AppHandle, raw_url: &str) {
    if let Ok(parsed) = Url::parse(raw_url) {
        let token = parsed
            .query_pairs()
            .find(|(k, _)| k == "token")
            .map(|(_, v)| v.to_string());
        let code = parsed
            .query_pairs()
            .find(|(k, _)| k == "code")
            .map(|(_, v)| v.to_string());
        let state = parsed
            .query_pairs()
            .find(|(k, _)| k == "state")
            .map(|(_, v)| v.to_string());
        let error = parsed
            .query_pairs()
            .find(|(k, _)| k == "error")
            .map(|(_, v)| v.to_string());
        let _ = auth::process_oauth_callback(app, token, code, state, error);
    }
}
